# Generated by Django 2.2.5 on 2019-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=5)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('degree', models.PositiveSmallIntegerField(default=0)),
                ('vehicle_id', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
