# Generated by Django 2.2.2 on 2019-06-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=5)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('azimuth', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
