# Generated by Django 2.2.2 on 2019-06-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
