# Generated by Django 2.2.2 on 2019-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_map', '0002_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
