# Generated by Django 2.2.2 on 2019-06-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_map', '0003_auto_20190609_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
