# Generated by Django 2.2.2 on 2019-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_map', '0005_auto_20190609_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[(1, 'Троллейбус'), (2, 'Автобус'), (3, 'Трамвай')], max_length=10),
        ),
    ]
